version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234cryptotax1234
      MYSQL_DATABASE: tax_reporter
    ports:
      - 3307:3306
    volumes:
      - ./data/db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080